# -*- coding: utf-8 -*-
"""abc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJeJdZGdgeccFK_K4HkYEmYIKO3n_vEI
"""

import pandas as pd

data = pd.read_excel("Employees.xlsx")

data.head()

data.info()

data.shape

data.isna().sum()

data.duplicated().sum()

data.head(3)

import matplotlib.pyplot as plt

data["Gender"].value_counts().sort_values(ascending = True).plot(kind ="pie")
plt.title("Pie Chart of Gender Column")
plt.ylabel("")
plt.show

data["Sick Leaves"].value_counts().sort_values(ascending = False).plot(kind ="pie")

plt.hist(data["Job Rate"])
plt.title("Histogram of Job Rate")
plt.xlabel("Rate")
plt.ylabel("Count")
plt.show()

data["Job Rate"].describe()

data.head()

data.groupby("Department")["Annual Salary"].mean().sort_values(ascending = False).head(7).plot(kind ="bar")
plt.title("Average Salary Graph by Department")
plt.xlabel("Department")
plt.ylabel("Average Salary")
plt.show()

data

data["Country"].unique()

data.groupby("Country")["Job Rate"].mean().sort_values(ascending = False).plot(kind ="bar")
plt.title("Job Rates by Countries")
plt.xlabel("Country")
plt.ylabel("Job Rate Average")
plt.show()

plt.hist(data["Overtime Hours"])
plt.title("Histogram of Overtime Hours")
plt.xlabel("Frequency")
plt.ylabel("Overtime Hours")
plt.show()

data["Overtime Hours"].describe()

data["Annual Salary"].describe()

data

data.columns

x = data[["Years","Job Rate"]]
y = data[["Annual Salary"]]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y , test_size = 0.2)

len(x_train)

len(y_train)

from sklearn.linear_model import LinearRegression

from sklearn.linear_model import LogisticRegression

# create model
lr = LogisticRegression()

# train
lr.fit(x_train, y_train)

# predict
y_pred = lr.predict(x_test)

predslr = lr.predict(x_test)

from sklearn.metrics import mean_absolute_error

mean_absolute_error(predslr,y_test)

x

pip install joblib

!pip install joblib

import joblib
joblib.dump(lr,"linearmodel.pkl")

pip install -r requirements.txt

!pip install streamlit joblib scikit-learn pyngrok

